yatube/about/urls.py
from django.urls import path
from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('posts/<int:post_id>/delete/', views.post_delete, name='post_delete'),
    path(
        'posts/<int:post_id>/comment/', views.add_comment, name='add_comment'
    ),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/yatube/urls.py
from django.urls import include, path
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]
handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'


if settings.DEBUG:
    import debug_toolbar
    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),) 
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model


User = get_user_model()
letters_in_title: int = 15


class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    description = models.TextField()

    def __str__(self) -> str:
        return self.title


class Post(models.Model):
    text = models.TextField(
        'Текст поста',
        help_text='Введите текст поста'
    )
    pub_date = models.DateTimeField(
        'Дата публикации',
        auto_now_add=True
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор'
    )
    group = models.ForeignKey(
        Group,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name='posts',
        verbose_name='Группа',
        help_text='Группа, к которой будет относиться пост'
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True
    )

    class Meta:
        ordering = ('-pub_date',)
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'

    def __str__(self):
        return self.text[:letters_in_title]


class Comment(models.Model):
    text = models.TextField(
        'Текст комментария',
        help_text='Введите текст комментария'
    )
    created = models.DateTimeField(
        'Дата поста',
        auto_now_add=True
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Автор'
    )
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Пост',
    )

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return self.text[:letters_in_title]


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        related_name='follower',
        on_delete=models.CASCADE,
    )
    author = models.ForeignKey(
        User,
        related_name='following',
        on_delete=models.CASCADE,
    )

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=['user', 'author'],
                name='unique_follow'
            )
        ]

yatube/posts/forms.py
from django import forms

from .models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['text', 'group', 'image']


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text', ]
    def __init__(self, *args, **kwargs):
        super(CommentForm, self).__init__(*args, **kwargs)
        self.fields['text'].widget.attrs['cols'] = 10
        self.fields['text'].widget.attrs['rows'] = 3

yatube/posts/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.views.decorators.cache import cache_page

from .models import Post, Group, User, Follow
from .forms import PostForm, CommentForm
from .utils import paginator_view

POSTS_ON_LIST: int = 10


def index(request):
    posts = Post.objects.all().select_related()
    page_obj = paginator_view(request, posts)
    index = request
    context = {'page_obj': page_obj, 'index': index}
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    posts = group.posts.all()
    page_obj = paginator_view(request, posts)
    context = {
        'group': group,
        'posts': posts,
        'page_obj': page_obj,
    }
    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    author = get_object_or_404(User, username=username)
    posts = author.posts.all()
    page_obj = paginator_view(request, posts)
    user = request.user
    following = request.user.is_authenticated and Follow.objects.filter(
        user=user, author=author
    ).exists()
    context = {
        'author': author,
        'posts': posts,
        'page_obj': page_obj,
        'following': following,
    }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    comments = post.comments.all()
    context = {
        'post': post,
        'form': CommentForm(),
        'comments': comments,
    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):
    if request.method == 'POST':
        form = PostForm(request.POST or None, files=request.FILES or None,)
        context = {'form': form, 'is_edit': False, }
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect('posts:profile', request.user.username)
        context = {'form': form, 'is_edit': False, }
        return render(request, 'posts/create_post.html', context)
    form = PostForm()
    context = {'form': form, 'is_edit': False, }
    return render(request, 'posts/create_post.html', context)


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    if request.user != post.author:
        return redirect("posts:post_detail", post_id=post_id)
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post
    )
    if form.is_valid():
        form.save()
        return redirect("posts:post_detail", post_id=post_id)
    else:
        context = {'form': form, 'is_edit': True, 'post': post}
        return render(request, 'posts/create_post.html', context)


@login_required
def post_delete(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    if request.user != post.author:
        return redirect("posts:post_detail", post_id=post_id)
    post.delete()
    return redirect('posts:profile', request.user.username)


@login_required
def add_comment(request, post_id):
    """Функция обработки формы добавления комментария"""
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    post_list = Post.objects.filter(author__following__user=request.user)
    page_obj = paginator_view(request, post_list)
    follow = request
    context = {
        'post_list': post_list,
        'page_obj': page_obj,
        'follow': follow,
    }
    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    author = get_object_or_404(User, username=username)
    user = request.user
    already_followed_user = Follow.objects.filter(user=request.user,
                                                  author=author).exists()
    if user == author:
        return redirect('posts:profile', username=username)
    if already_followed_user:
        return redirect('posts:profile', username=username)
    Follow.objects.create(user=request.user, author=author)
    return redirect('posts:profile', username=username)


@login_required
def profile_unfollow(request, username):
    author = get_object_or_404(User, username=username)
    follow_qs = Follow.objects.filter(author=author, user=request.user)
    if follow_qs.exists():
        follow_qs.delete()
    return redirect('posts:profile', username=username)

yatube/templates/posts/create_post.html
{% extends 'base.html' %}
{% block title %}
  {% if not is_edit %}
    Добавить запись  
  {% else %} 
    Редактировать запись
  {% endif %}
{% endblock %} 
{% block content %}
{% with request.resolver_match.view_name as view_name %}  
      <div class="container py-5">
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">       
                {% if not is_edit %}
                  Добавить запись  
                {% else %} 
                  Редактировать запись
                {% endif %}
                            
              </div>
              <div class="card-body">        
                <form method="post" enctype="multipart/form-data" action=" {% if not is_edit%}
                                                                         {% url 'posts:post_create'%}
                                                                         {% else %}
                                                                        {% url 'posts:post_edit' post_id=post.id%}
                                                                       {% endif %}" >
                                           
                  {% csrf_token%}
                  

                  <div class="form-group row my-3 p-3">
                    <label for="id_text">
                      Текст поста                  
                      <span class="required text-danger" >*</span>                  
                    </label>
                    {{form.text}}
                    <br>
                      <small id="id_text-help" class="form-text text-muted">
                        Текст нового поста
                      </small>  
                  </div> 
                  <div class="form-group row my-3 p-3">
                    <label for="id_group">
                      Группа                  
                    </label>
                    {{form.group }} 
                      <br>
                        <small id="id_group-help" class="form-text text-muted">
                          Группа, к которой будет относиться пост
                        </small>
                  </div>
                  {{form.image}}

                  <div class="d-flex justify-content-end">
                    <button type="submit" class="btn btn-primary">
                      {% if not is_edit %}
                      Добавить  
                      {% else %} 
                     Сохранить
                     {% endif %}
                    </button>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
{% endwith %} 
{% endblock %} 

yatube/templates/posts/follow.html
{% extends 'base.html' %}
{% block title %}
  Последние обновления на сайте.
{% endblock %} 
{% block content %}
{% include 'posts/includes/switcher.html' %}
{% load thumbnail %}
{% load cache %}
{% cache 20 follow_page %}

  {% for post in page_obj %}
    <div class="container py-5">     
        <ul>
          <li>
            Автор: {{ post.author.get_full_name }}
            <a href="{% url 'posts:profile' post.author.username %}">
              все посты пользователя
            </a>
          </li>
          <li>
            Дата публикации: {{ post.pub_date|date:"d E Y" }}
          </li>
        </ul>
        {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
          <img class="card-img my-2" src="{{ im.url }}">
       {% endthumbnail %}
        <p>{{ post.text }}</p>    
      
      {% if post.group %}   
        <p>Группа: {{post.group}}</p>
        <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
        <br><a href="{% url 'posts:post_detail' post.pk %}">подробная информация</a>
      {% endif %}
     {% if not forloop.last %}<hr>{% endif %}
    </div>  
    {% endfor %}
    {% endcache %}
  {% include 'posts/includes/paginator.html' %}
{% endblock %} 

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% block title %}
  {{group.title}}
{% endblock %} 
{% block content %}
{% load thumbnail %}
  <div class="container py-5">     
    <h1>{{group.title}}</h1>
      <p>{{group.description}}</p> 
        {% for post in posts %}
           <ul>
            <li>
              Автор: {{ post.author.get_full_name }}
              <a href="{% url 'posts:profile' post.author.username %}">
                все посты пользователя
              </a>
            </li>
            <li>
               Дата публикации: {{ post.pub_date|date:"d E Y" }}
            </li>
          </ul>
          {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
          <img class="card-img my-2" src="{{ im.url }}">
          {% endthumbnail %}
           <p>{{ post.text }}</p> 
           <br><a href="{% url 'posts:post_detail' post.pk %}">подробная информация</a>   
           {% if not forloop.last %}<hr>{% endif %}
       {% endfor %} 
  </div>  
{% include 'posts/includes/paginator.html' %}
{% endblock %} 

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% block title %}
  Последние обновления на сайте.
{% endblock %} 
{% block content %}
{% include 'posts/includes/switcher.html' %}
{% load thumbnail %}

<div class="container py-5">
  
<h1>Последние обновления на сайте</h1>
{% load cache %}
{% cache 20 index_page %}
{% for post in page_obj %}   

        <ul>
          <li>
            Автор: {{ post.author.get_full_name }}
            <a href="{% url 'posts:profile' post.author.username %}">
              все посты пользователя
            </a>
          </li>
          <li>
            Дата публикации: {{ post.pub_date|date:"d E Y" }}
          </li>
        </ul>
        {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
          <img class="card-img my-2" src="{{ im.url }}">
       {% endthumbnail %}
       
        <p>{{ post.text }}</p>    
      
      {% if post.group %}   
        <p>Группа: {{post.group}}</p>
        <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
        
      {% endif%}
        <br><a href="{% url 'posts:post_detail' post.pk %}">подробная информация</a>
      
     {% if not forloop.last %}<hr>{% endif %}
   
    {% endfor %}
    {% endcache %}
  </div>  
   
  {% include 'posts/includes/paginator.html' %}
{% endblock %} 

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% block title %}
Пост {{ post.text|truncatechars:30 }}
{% endblock %}
{% block content %}
  {% load static %}
  {% load thumbnail %}
  {% load user_filters %}
  <div class="container py-5">
      <div class="row">
        <aside class="col-12 col-md-3">
          <ul class="list-group list-group-flush">
            <li class="list-group-item">
              Дата публикации:  {{ post.pub_date|date:"d E Y" }}
            </li>
            {% if posts.group %} 
              <li class="list-group-item">
                Группа: {{posts.group}}
                  <a href="{% url 'posts:group_list' post.group.slug %}">
                    все записи группы
                  </a>
              </li>
            {% endif %}
              <li class="list-group-item">
                Автор: {{post.author.get_full_name}}
              </li>
              <li class="list-group-item d-flex justify-content-between align-items-center">
              Всего постов автора:  <span >{{post.author.posts.count}}</span>
              </li>
              <li class="list-group-item">
                <a href="{% url 'posts:profile' post.author.username %}">
                  все посты пользователя
                </a>
              </li>
          </ul>
        </aside>
        <article class="col-12 col-md-9">
          
          {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
          <img class="card-img my-2" src="{{ im.url }}">
        {% endthumbnail %}
      
  
          <p>
           {{post.text}}
          </p>
          
          {% if request.user == post.author %}
          <a class="btn btn-primary" href="{% url 'posts:post_edit' post.pk %}">
            Редактировать запись
          </a>
          <a class="btn btn-primary" href="{% url 'posts:post_delete' post.pk %}">
            Удалить запись
          </a>
          {%endif%}

          {% if user.is_authenticated %}
          <div class="card my-4">
            <h5 class="card-header">Добавить комментарий:</h5>
            <div class="card-body">
              <form method="post" action="{% url 'posts:add_comment' post.id %}">
                {% csrf_token %}      
                <div class="form-group mb-2">
                  {{ form.text|addclass:"form-control" }}
                </div>
                <button type="submit" class="btn btn-primary">Отправить</button>
              </form>
            </div>
          </div>
        {% endif %}
      
        {% for comment in comments %}
          <div class="media mb-4">
            <div class="media-body">
              <h5 class="mt-0">
                <a href="{% url 'posts:profile' comment.author.username %}">
                  {{ comment.author.username }}
                </a>
              </h5>
                <p>
                 {{ comment.text }}
                </p>
              </div>
            </div>
        {% endfor %}      
      </article>

        
      </div> 
    </div>
{% endblock %} 

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% block title %}
Профайл пользователя {{author.get_full_name}}
{% endblock %} 
{% block content %}
{% load static %}
{% load thumbnail %}

      <div class="container py-5">        
        <h1>Все посты пользователя {{ author.get_full_name }} </h1>
          <h3>Всего постов:  {{ author.posts.count }} </h3>
          {% if request.user != author %}
          {% if user.is_authenticated %}
          {% if following %}
          <a
            class="btn btn-lg btn-light"
            href="{% url 'posts:profile_unfollow' author.username %}" role="button"
          >
            Отписаться
          </a>
        {% else %}
            <a
              class="btn btn-lg btn-primary"
              href="{% url 'posts:profile_follow' author.username %}" role="button"
            >
              Подписаться
            </a>
         {% endif %}
         {% endif %}
         {% endif %}
           
          {% for post in posts %}
            <article>
              <ul>
                <li>
                  Автор: {{ post.author.get_full_name }}
                    <a href="{% url 'posts:profile' post.author.username %}">
                      все посты пользователя
                    </a>
                </li>
                <li>
                  Дата публикации: {{ post.pub_date|date:"d E Y" }}
                </li>
              </ul>
              {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
              <img class="card-img my-2" src="{{ im.url }}">
             {% endthumbnail %}
              <p>
                {{ post.text }}
              </p>
              <a href="{% url 'posts:post_detail' post.pk%}">подробная информация </a>
            </article>  
            <br> 
            {% if post.group %}   
            <p>Группа: {{post.group}}</p> 
              <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>    
               
            {% endif %}
            <hr>
         {% endfor %}
        {% if not forloop.last %}<hr>{% endif %}
      </div>
  {% include 'posts/includes/paginator.html' %}
{% endblock %} 